import React, { useMemo, useState } from "react";
import { ResumeTemplatePanel } from "../components/results/ResumeTemplatePanel.jsx";
import { RunSelector } from "../components/application/RunSelector.jsx";
import { resumeAccents, sampleResult } from "../data.js";
import { getRunResult, normalizeResult } from "../resultUtils.js";
import { useRuns } from "../hooks/useRuns.js";

export function ResumeModulePage({ initialRunId = "" }) {
  const { error, runs, selectedRun, selectedRunId, setSelectedRunId } = useRuns(initialRunId);
  const [resumeTemplate, setResumeTemplate] = useState("compact");
  const [resumeAccent, setResumeAccent] = useState(resumeAccents[0]);
  const result = useMemo(
    () => (selectedRun ? getRunResult(selectedRun) : normalizeResult(sampleResult)),
    [selectedRun]
  );

  return (
    <main className="pageShell">
      <section className="pageHeader compactHeader">
        <div>
          <span>Resume</span>
          <h1>Generate a targeted resume for a selected role.</h1>
        </div>
        <p>
          Choose a saved target job, select a resume template, then export a role-specific draft.
        </p>
      </section>

      {error ? <p className="error">{error}</p> : null}

      <section className="moduleGrid">
        <aside className="moduleControls">
          <h2>Target setup</h2>
          <RunSelector
            runs={runs}
            selectedRunId={selectedRunId}
            onSelectRun={setSelectedRunId}
          />
          <p>
            Resume content is generated by the application workflow. Run a match first if you do
            not see the role you need.
          </p>
        </aside>
        <ResumeTemplatePanel
          result={result}
          resumeAccent={resumeAccent}
          resumeTemplate={resumeTemplate}
          onAccentChange={setResumeAccent}
          onTemplateChange={setResumeTemplate}
        />
      </section>
    </main>
  );
}
